<?php

namespace ExerciseBundle\Repository;

/**
 * KnightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KnightRepository extends \Doctrine\ORM\EntityRepository 
{
}
